name: "Learning Github action"

on:
  push:
    branches: 
      - dev
      # - develop
      - aq

jobs:
  checkout:
    name: "checkout"
    runs-on: ubuntu-latest
    steps: 
      - name: checkout the source code
        uses: actions/checkout@v3
          
  list_buckets:
    name: "list_buckets"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"
    steps: 
      - name: Check the AWS cli version and syst info
        run: |
          cat /etc/*release
          aws --version
      - name: "List s3 buckets"
        run: |
          aws s3 ls
          ls -l

  run_python_script:
    name: "run_python_script"
    runs-on: ubuntu-latest
    steps: 
      - name: checkout the source code
        uses: actions/checkout@v3

      - name: Run python script 
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: execute the python script 
        run: |
          cd python
          ls -l 
          chmod +x script.py
          python script.py

  run_terraform:
    name: "run_terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"
    steps: 
      - name: Install terraform 
        run: |
          sudo apt update
          sudo apt install wget -y 
          wget https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
          sudo unzip terraform_1.0.0_linux_amd64.zip
          sudo mv terraform /usr/local/bin
          terraform -version

      - name: checkout the source code
        uses: actions/checkout@v3

      - name: terraform plan
        run: |
          cd terraform 
          ls -l 
          terraform init
          terraform validate
          terraform fmt
          terraform plan
          terraform apply -auto-approve

  docker-build:
    name: "docker-build"
    runs-on: ubuntu-latest
    steps: 

      - name: checkout the source code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        env:
          ECR_REGISTRY: 788210522308.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: github_action
          IMAGE_TAG: html_apps
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push image to dockerhub and ECR
        run: |
          docker --version 
          cd app 
          ls

          echo "PBuilding The image..."
          docker build -t html_apps .
          docker tag html_apps:latest leonardtia/github-ation:html_apps
          # docker tag html_apps:latest 788210522308.dkr.ecr.us-east-1.amazonaws.com/applications:$MAGE_TAG

          echo "Pushing image to Docker Hub..."
          docker push leonardtia/github-ation:html_apps

          # echo "Pushing image to ECR..."
          # docker push 788210522308.dkr.ecr.us-east-1.amazonaws.com/applications:$MAGE_TAG
          