name: "Learning Github action"

on:
  push:
    branches: 
      - dev
      # - develop
      - aq

jobs:
  checkout:
    name: "checkout"
    runs-on: ubuntu-latest
    steps: 
      steps: 
        - name: checkout the source code
          uses: actions/checkout@v3
        - name: checkout the source code2
          run: |
          ls -l
          
  list_buckets:
    name: "list_buckets"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"
    steps: 
      - name: Check the AWS cli version and syst info
        run: |
          cat /etc/*release
          aws --version
      - name: "List s3 buckets"
        run: |
          aws s3 ls
          ls -l

  run_python_script:
    name: "run_python_script"
    runs-on: ubuntu-latest
    steps: 
      # - name: checkout the source code
      #   uses: actions/checkout@v3

      - name: Run python script 
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: execute the python script 
        run: |
          cd python
          ls -l 
          chmod +x script.py
          python script.py

  # run_terraform:
  #   name: "run_terraform"
  #   runs-on: ubuntu-latest
  #   steps: 
  #     - name: Install terraform 
  #       run: |
  #         wget https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
  #         unzip terraform_1.0.0_linux_amd64.zip
  #         ./terraform

  #         ### Move the binary to the path so that you can run Terraform from any location
  #         mv terraform /usr/local/bin
  #         terraform -version


  #     - name: checkout the source code
  #       uses: actions/checkout@v3

  #     - name: Run python script 
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.9'
          
  #     - name: execute the python script 
  #       run: |
  #         cd python
  #         ls -l 
  #         chmod +x script.py
  #         python script.py





    