name: "Terraform Plan"

on:
  push:
    branches: 
      - master

jobs:
  authentification:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"

    steps: 
      - name: checkout 
        uses: actions/checkout@v2

      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.3.7"
          cli_config_credentials_token: ${{ secrets.CLI_CONFIG_CREDENTIALS_TOKEN }}

      - name: Terraform Init
        id: init
        run: |
          cd terraform-remote
          terraform init

      - name: Terraform Validate
        id: validate
        run: |
          cd terraform-remote
          terraform fmt
          terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          cd terraform-remote
          terraform plan
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      
      - name: Terraform Apply
        run: |
          cd terraform-remote
          terraform apply -auto-approve