name: "Terraform Plan"

on:
  push:
    branches: 
      - dev
      - develop

jobs:
  authentification:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"

    steps: 
      - name: checkout 
        uses: actions/checkout@v2

      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.3.7"
          cli_config_credentials_token: ${{ secrets.CLI_CONFIG_CREDENTIALS_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: |
          terraform fmt
          terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

  aws:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"

    steps: 
      - name: awscli
        run: |
          cat /etc/*release
          aws --version
          apt update
          apt install unzip -y 
          apt install curl -y
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
          ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
          aws --version
      - name: check buckets
        run: |
          aws s3 ls



    
        